spring.application.name=demo-for-aug2026
spring.datasource.url=jdbc:mysql://localhost:3306/aug2026?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=roottoor
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
JWT_SECURITY_KEY=china_key
COUNTRY=china